### PR TITLE
Showing claims in Support

### PR DESCRIPTION
**Pull request by simonwhatley**
Add a way for a support user to list, filter, view and download all claims submitted by schools.

### CODE REVIEW

**Comment by simonwhatley** [comment]
[Showing claims in Support](https://trello.com/c/4RAMChoc/215-showing-claims-in-support)

**Comment by simonwhatley** [comment]
[Showing claims in Support](https://trello.com/c/4RAMChoc/215-showing-claims-in-support)

**Review by olioldfield — COMMENTED** [review]
This one is beyond me!

**Comment by simonwhatley** [comment]
> This one is beyond me!

I will create some dummy data to make it easier for you to review. Otherwise, you'll need to add some claims to be able to see them in the main claims list.

**Comment by olioldfield** [comment]
Ahh that would be very helpful!

Thank you

Oli

**Review by Nitemaeric — COMMENTED** [review]
This PR made my M1 Pro struggle...

CleanShot 2024-04-02 at 10 22 35

It would be better to put the claim seeds into a single `claims.json` file, similar to the `teachers.json`. A large array of objects instead of an object per file.

**Review by olioldfield — APPROVED** [review]

**Comment by simonwhatley** [comment]
@Nitemaeric, I'll optimise the claims in a separate PR.

**Pull request merged**
