### PR TITLE
State that claim will be shared with the accredited provider

### PR DESCRIPTION
**Pull request by simonwhatley**
On the claim confirmation screen, state that `This claim will be shared with {{ accredited provider }}`.

### CODE REVIEW

**Comment by simonwhatley** [comment]
[Informing schools that the claim will be shared with providers](https://trello.com/c/9m7e0tlp/361-informing-schools-that-the-claim-will-be-shared-with-providers)

**Comment by Nitemaeric** [comment]
Should we present this information to the user _before_ they submit?

**Comment by olioldfield** [comment]
I think given we have added in quite a bit of friction to the add a claim journey between UR and going pbl live (adding in d.o.b and advising mentors need to be informed and shown the privacy notice), it going in the what happens next section makes sense at the moment. However, we can keep it under review and potentially move it for public beta?

**Review by olioldfield — APPROVED** [review]

**Comment by simonwhatley** [comment]
[Private beta providers are informed of claims where they have been listed](https://trello.com/c/TESXfXRt/262-private-beta-providers-are-informed-of-claims-where-they-have-been-listed)

**Pull request merged**
