### PR TITLE
Add claim flow

### PR DESCRIPTION
**Pull request by simonwhatley**

### CODE REVIEW

**Comment by simonwhatley** [comment]
[Make a claim - design](https://trello.com/c/1wX0gYeO/123-make-a-claim-design)

**Review by CatalinVoineag — COMMENTED** [review]
This looks good to me. My only question is about the change button on the `Check your answers page`. The only `change` button that seems to work is the provider one.

Will the change functionality for mentors and hours come at a later date? I should say there's is enough work for us to crack on.

Screenshot from 2024-02-16 09-32-36

**Comment by simonwhatley** [comment]
> Will the change functionality for mentors and hours come at a later date? I should say there's is enough work for us to crack on.

Yep, we'll code the change links in a separate PR.

**Review by CatalinVoineag — COMMENTED** [review]
Is there any formatting requiremenets around the reference? 
Screenshot from 2024-02-16 09-38-32

Or is just a random 8 characters unique string?

**Review by LeaWelch — APPROVED** [review]

**Comment by simonwhatley** [comment]
> Are there any formatting requirements around the reference?

We need to:

- find out what the reference number format will be - in the prototype, we've used an 8-character alphanumeric
- if there is a visual layout - for example, two groups of 4 characters
- if the reference should ignore certain characters - 0 (number) vs O (letter)
- if the reference should be displayed in a different font.

**Pull request merged**
