### PR TITLE
Add date of birth to finding teacher in add mentor flow

### PR DESCRIPTION
**Pull request by simonwhatley**
Use these [example (fake) teachers](https://docs.google.com/spreadsheets/d/117VpQBGz1D9P8E1rGL786XFANxodMD8VxKGNSsGGbEo/edit) to test this feature.

### CODE REVIEW

**Comment by simonwhatley** [comment]
[Add D.O.B to the add a mentor journey so users need to input this + TRN to look-up a mentor's first name and last name](https://trello.com/c/KO1tb2WC/379-add-dob-to-the-add-a-mentor-journey-so-users-need-to-input-this-trn-to-look-up-a-mentors-first-name-and-last-name)

**Review by olioldfield — APPROVED** [review]
Pattern looks great, but I would remove "We do not store date of birth" - think it may add additional, unnecessary friction to the journey.

**Review by LeaWelch — APPROVED** [review]

**Comment by olioldfield** [comment]
Think the drop down text needs amending to reflect that it is their mentor's TRN and not theirs:

If your mentor does not have a TRN, share the [teacher reference number (TRN) guidance with them (opens in new tab)](https://www.gov.uk/guidance/teacher-reference-number-trn) to find a lost TRN, or apply for one.

The example date of birth looks a bit weird - is it possible to separate the day, month and year somehow.

Also, as the flow is being updated would it make sense to action this at the same time in the Add Mentor, check your answers page?

I confirm that <mentor name> has been told that their information will be stored in line with our privacy notice.

**Review by Nitemaeric — APPROVED** [review]

**Comment by olioldfield** [comment]
Sounds great - thanks!

**Pull request merged**
