### PR TITLE
Handling duplicate mentor provider claims

### PR DESCRIPTION
**Pull request by petejobeskinandcarta**
This is changes to the 'mentors' and 'hours' pages within the add claim flow.

* Display a details component explaining why not all mentors might be shown in the list (the list now only displays Mentors who can be claimed against)
* Display an inset text that explains how many hours are left to claim for a mentor and why.
* Add question legends under these components to maintain visual relationship and accessibility of label and inputs.

It does not dynamically store or transmit the number of hours remaining for the mentor for each provider.

### CODE REVIEW

**Comment by petejobeskinandcarta** [comment]
Can we pause on reviewing this one, I need to make a couple of updates to content.

**Comment by simonwhatley** [comment]
[Design how we handle duplicate mentor-provider claims](https://trello.com/c/jYVqz6NH/176-design-how-we-handle-duplicate-mentor-provider-claims)

**Comment by simonwhatley** [comment]
Some notes on the changes:

**Mentor page**

| Happy path | Unhappy path |
| --- | --- |
| Screenshot 2024-04-22 at 12 23 55@2x | Screenshot 2024-04-22 at 12 25 35@2x |

In the first instance, the claims will likely follow the ‘happy path’ since no legacy claims exist.
In this instance, we keep the mentor list as simple as possible. There is no need for extra messaging, and users can claim all their mentors.

The second time users encounter this screen, we show a message if some mentor-provider relationships can no longer be claimed.

Like the ‘Hours of training’ page, we show the message as inset text between the heading and the question label if the problem exists. 

If users have claimed for the funding for all their mentors, we show an empty state.

**Hours of training page**

| Happy path | Unhappy path |
| --- | --- |
| Screenshot 2024-04-22 at 12 24 58@2x | Screenshot 2024-04-22 at 12 25 55@2x |

In the first instance, the claims will likely follow a ‘happy path’ since no legacy claims exist.

In this instance, we keep the hours screen as simple as possible. There is no need for any extra messaging. Users can either claim the total 20 hours or a smaller amount.

The second time users encounter this screen, and if the mentor-provider relationship has already been claimed, we show the message saying the hours they can claim are reduced because they (or another school) have already claimed some hours (for the mentor-provider) relationship.

We:
- highlight the remaining hours in the inset text
- adapt the radio option to be the remaining hours - for example, “7 hours”
- adapt the ‘Another amount’ hint text to be up to the remaining hours
- adapt the error messages to match the remaining hours

**Review by olioldfield — APPROVED** [review]
All looks great - only comment for consideration is that we add 
view claims hyperlink and contact email into this text:

This list includes all mentors who can be included on a claim. If a mentor you have added is not showing in this list, that is because they have already had 20 hours of training claimed for with this provider.

Training may have been claimed for by a different school. View claims to review your claims, or contact [ittmentor.funding@ducation.gov.uk](mailto:ittmentor.funding@ducation.gov.uk) if you think there is a problem.

**Review by Nitemaeric — APPROVED** [review]
🙌

**Comment by simonwhatley** [comment]
@olioldfield I think this is confusing:

> This list includes all mentors who can be included on a claim. If a mentor you have added is not showing in this list, that is because they have already had 20 hours of training claimed for with Best Practice Network.
>
> A different school may have claimed for the mentors’ training at Best Practice Network. View claims to [review your claims](#), or contact [ittmentor.funding@ducation.gov.uk](#) if you think there is a problem.

So I’m going to simplify to:

> This list includes all mentors who can be included on a claim. If a mentor you have added is not showing in this list, that is because they have already had 20 hours of training claimed for with Best Practice Network.
>
> Contact [ittmentor.funding@ducation.gov.uk](#) if you think there is a problem.

I’m removing the ‘other’ school element for now, as that might be confusing/alarming. And we don’t know how often that situation may occur, if at all.

**Pull request merged**
